name: Build 6.1.3 wordpress image

# on:
#   push:
#     branches:
#       - test-CICD

# Controls when the action will run.
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  wp-apache611:
    runs-on: ubuntu-latest

    steps:
      # - name: Checkout repository
      #   uses: actions/checkout@v2

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push WordPress image
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./php8.0-apache-6.1.3/Dockerfile
          builder: docker/setup-buildx-action@v1
          platforms: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wordpress:apache-6.1.3
